# Generated by Django 6.0.2 on 2026-02-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_area_customerprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='area',
        ),
    ]
