# Generated by Django 6.0.2 on 2026-02-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phoneotp_userphone'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='accounts.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_prices', to='services.service')),
            ],
            options={
                'unique_together': {('provider_profile', 'service')},
            },
        ),
    ]
